// <auto-generated />
using System;
using GroceryControl.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GroceryControl.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GroceryControlDbContext))]
    [Migration("20260318180430_AddFavoritesTemplatesExpiry")]
    partial class AddFavoritesTemplatesExpiry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroceryControl.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DefaultUnitCategory")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultUnitCategory = 0,
                            Description = "Leche, queso, yogur y derivados lácteos",
                            IconName = "milk",
                            Name = "Lácteos",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            DefaultUnitCategory = 1,
                            Description = "Carnes rojas, aves, cerdo y embutidos",
                            IconName = "meat",
                            Name = "Carnes",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            DefaultUnitCategory = 3,
                            Description = "Frutas frescas, verduras y hortalizas",
                            IconName = "apple",
                            Name = "Frutas y Verduras",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            DefaultUnitCategory = 1,
                            Description = "Arroz, avena, cereales y granos",
                            IconName = "grain",
                            Name = "Cereales y Granos",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            DefaultUnitCategory = 0,
                            Description = "Agua, jugos, refrescos y bebidas",
                            IconName = "drink",
                            Name = "Bebidas",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            DefaultUnitCategory = 0,
                            Description = "Productos de limpieza para el hogar",
                            IconName = "cleaning",
                            Name = "Limpieza",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            DefaultUnitCategory = 3,
                            Description = "Jabón, shampoo, pasta dental y cuidado personal",
                            IconName = "hygiene",
                            Name = "Higiene Personal",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            DefaultUnitCategory = 3,
                            Description = "Conservas, atún, frijoles y productos enlatados",
                            IconName = "can",
                            Name = "Enlatados",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            DefaultUnitCategory = 0,
                            Description = "Salsas, especias, aceites y aderezos",
                            IconName = "seasoning",
                            Name = "Condimentos",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            DefaultUnitCategory = 3,
                            Description = "Pan, tortillas, bollería y repostería",
                            IconName = "bread",
                            Name = "Panadería",
                            SortOrder = 10
                        });
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.InventoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime?>("ExpirationDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MinimumThreshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitTypeId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("InventoryEntries", (string)null);
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.PriceSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ObservedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("UnitTypeId");

                    b.HasIndex("ProductId", "StoreId", "ObservedDateUtc");

                    b.ToTable("PriceSuggestions", (string)null);
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DefaultQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("DefaultUnitTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasFilter("\"Barcode\" IS NOT NULL");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DefaultUnitTypeId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("PurchaseDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId", "PurchaseDateUtc");

                    b.ToTable("Purchases", (string)null);
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.PurchaseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AddToInventory")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("UnitTypeId");

                    b.ToTable("PurchaseItems", (string)null);
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.ShoppingTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingTemplates");
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.ShoppingTemplateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UnitTypeId");

                    b.ToTable("ShoppingTemplateItems");
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Branch")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.UnitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("ConversionFactorToBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("MeasurementUnit")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UnitCategory")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UnitTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "ml",
                            ConversionFactorToBase = 1m,
                            MeasurementUnit = 0,
                            Name = "Mililitros",
                            UnitCategory = 0
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "L",
                            ConversionFactorToBase = 1000m,
                            MeasurementUnit = 1,
                            Name = "Litros",
                            UnitCategory = 0
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "g",
                            ConversionFactorToBase = 1m,
                            MeasurementUnit = 2,
                            Name = "Gramos",
                            UnitCategory = 1
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "kg",
                            ConversionFactorToBase = 1000m,
                            MeasurementUnit = 3,
                            Name = "Kilogramos",
                            UnitCategory = 1
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "ud",
                            ConversionFactorToBase = 1m,
                            MeasurementUnit = 4,
                            Name = "Unidad",
                            UnitCategory = 3
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "pz",
                            ConversionFactorToBase = 1m,
                            MeasurementUnit = 5,
                            Name = "Pieza",
                            UnitCategory = 3
                        });
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.UserFavoriteProduct", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("UserFavoriteProducts");
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("HouseholdSize")
                        .HasColumnType("integer");

                    b.Property<string>("PreferredCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("PurchaseFrequency")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.InventoryEntry", b =>
                {
                    b.HasOne("GroceryControl.Domain.Entities.Product", "Product")
                        .WithMany("InventoryEntries")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryControl.Domain.Entities.UnitType", "UnitType")
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryControl.Domain.Entities.User", "User")
                        .WithMany("InventoryEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("UnitType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.PriceSuggestion", b =>
                {
                    b.HasOne("GroceryControl.Domain.Entities.Product", "Product")
                        .WithMany("PriceSuggestions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroceryControl.Domain.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryControl.Domain.Entities.UnitType", "UnitType")
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");

                    b.Navigation("UnitType");
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.Product", b =>
                {
                    b.HasOne("GroceryControl.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryControl.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GroceryControl.Domain.Entities.UnitType", "DefaultUnitType")
                        .WithMany("Products")
                        .HasForeignKey("DefaultUnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DefaultUnitType");
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.Purchase", b =>
                {
                    b.HasOne("GroceryControl.Domain.Entities.Store", "Store")
                        .WithMany("Purchases")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryControl.Domain.Entities.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.PurchaseItem", b =>
                {
                    b.HasOne("GroceryControl.Domain.Entities.Product", "Product")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryControl.Domain.Entities.Purchase", "Purchase")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroceryControl.Domain.Entities.UnitType", "UnitType")
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");

                    b.Navigation("UnitType");
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.ShoppingTemplate", b =>
                {
                    b.HasOne("GroceryControl.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.ShoppingTemplateItem", b =>
                {
                    b.HasOne("GroceryControl.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GroceryControl.Domain.Entities.ShoppingTemplate", "Template")
                        .WithMany("Items")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroceryControl.Domain.Entities.UnitType", "UnitType")
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Template");

                    b.Navigation("UnitType");
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.Store", b =>
                {
                    b.HasOne("GroceryControl.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.UserFavoriteProduct", b =>
                {
                    b.HasOne("GroceryControl.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroceryControl.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("GroceryControl.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("GroceryControl.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.Product", b =>
                {
                    b.Navigation("InventoryEntries");

                    b.Navigation("PriceSuggestions");

                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.Purchase", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.ShoppingTemplate", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.Store", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.UnitType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GroceryControl.Domain.Entities.User", b =>
                {
                    b.Navigation("InventoryEntries");

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
